### ISSUE TITLE
[OpenPro]阅读云原生安全领域论文并进行分享

### ISSUE THREAD

**Issue by JingbenShi668** [X-lab2017/open-research#100]
### Title

Security Challenges in the Container Cloud

### Link

https://xlab2017.yuque.com/msdpvs/dtg7ew/26404277
https://ieeexplore.ieee.org/document/9750244

### Year

2021

### Conference or Journal

[2021 Third IEEE International Conference on Trust, Privacy and Security in Intelligent Systems and Applications (TPS-ISA)](https://ieeexplore.ieee.org/xpl/conhome/9750214/proceeding)

### Rank

IEEE

### Keywords

Container security, Namespaces, Control groups, Docker, Kubernetes

### Reason for Recommending

探索从安全角度考虑以docker为代表的云原生技术；安全优化的思路值得借鉴参考

**Comment by will-ww** [comment]
感觉是篇容器安全的综述文章，看看能否有些启发性工作~

**Comment by JingbenShi668** [comment]
> 感觉是篇容器安全的综述文章，看看能否有些启发性工作，对容器进行分层研究的思路挺不错~

对的，是一篇综述类文档，对容器安全的分析还是蛮全面的，在容器安全考量和加固上会有蛮多的思路～😊

**Comment by JingbenShi668** [comment]
论文相关文档，用于补充理解论文，可点击下载，😊
[论文材料](https://xlab-open-source.oss-cn-beijing.aliyuncs.com/paper-data/Security_Challenges_in_the_Container_Cloud.pdf)
[论文分享大纲](https://xlab-open-source.oss-cn-beijing.aliyuncs.com/paper-data/6_20%E3%80%8ASecurity%20Challenges%20in%20the%20Container%20Cloud%E3%80%8B.pdf)
[论文分享详细文档](https://xlab-open-source.oss-cn-beijing.aliyuncs.com/paper-data/6_20%E8%AE%BA%E6%96%87%E5%88%86%E4%BA%AB_%E8%AF%A6%E7%BB%86%E6%96%87%E6%A1%A3.docx)
