### ISSUE TITLE
[22-23秋] 2022 年 9 月 12 日第一次开源研究研讨会

### ISSUE THREAD

**Issue by will-ww** [X-lab2017/open-research#112]
### Description

根据新学期[总体安排](https://github.com/X-lab2017/open-research/blob/main/agenda/%F0%9F%8D%812022-2023-Autumn-Term-OS-Seminar.md)，第一次研讨会主题为：新学期开源研究计划 & XSOSI 复盘

- 新学期开源研究计划（30min） @will-ww 
- XSOSI 复盘（30min） @frank-zsy 

欢迎大家参加，提出各种想法，在该 issue 下面进行讨论~

注：为配合 XSOSI 的实践，接下来的所有研讨、科研、工程等活动均尽量在 GitHub 上进行开放式运营~

**Comment by will-ww** [comment]
前30分钟的时间，我将大致说三个方面的内容：

- 新学期的总体安排与主要变化（[安排](https://github.com/X-lab2017/open-wonderland/blob/main/%F0%9F%8D%812022-2023-Autumn-Term-Activities-Schedule.md)，变化）
- [新学期开源研究计划](https://github.com/orgs/X-lab2017/discussions/176)

**Comment by frank-zsy** [comment]
XSOSI 复盘内容包含：
- 过去三个月的 XSOSI 数据情况
- XSOSI 本学期迭代计划说明
- XSOSI 算法的价值主张

**Comment by will-ww** [comment]
帖一章业务架构图（应用驱动创新）：

![image](https://user-images.githubusercontent.com/15010826/189590027-180dacc5-0424-432b-84f9-379fba89911a.png)

**Comment by will-ww** [comment]
新学期第一次启动会，很开兴给大家介绍~

**Comment by bifenglin** [comment]
新学期，冲！

**Comment by wengzhenjie** [comment]
新学期顺利毕业～

**Comment by wj23027** [comment]
大家好，未来大家多多指教！

**Comment by xgdyp** [comment]
大家好，未来大家多多指教！

**Comment by YuxinLi1** [comment]
新学期，加油！

**Comment by birdflyi** [comment]
加油

**Comment by longyanz** [comment]
新学期加油~

**Comment by xiaoya-yaya** [comment]
Hi

**Comment by yoyo-wu98** [comment]
hi~

**Comment by xgdyp** [comment]
Hello World

**Comment by zhicheng-ning** [comment]
> 新学期顺利毕业～

借汝评论，予吾发之。赠汝五毛，购一卫龙，与众人分食，岂不快哉？

**Comment by will-ww** [comment]
> 想在真实场景中实践Git/GitHub吗？欢迎学弟学妹来参与[Hypercrx](https://github.com/hypertrons/hypertrons-crx)呀~

开始拉票了，哈哈~

**Comment by Laceyoo** [comment]
明天又是元气满满的一天～😄

**Comment by veronipp** [comment]
newcomer～

**Comment by Zi1l** [comment]
新的阶段，加油！

**Comment by gymgym1212** [comment]
刚好有个笔试时间撞了，可惜没能赶上会议。看到有好多新伙伴🤩 ，也祝大家新学期新气象

**Comment by yfsn666** [comment]
新学期，冲冲冲！

**Comment by LPY22** [comment]
来了，新学期大家好！

**Comment by andyhuang18** [comment]
新的阶段，大家共同努力，向优秀的学长学姐学习！！

**Comment by Best549** [comment]
2022向前冲！！！

**Comment by 1600383075** [comment]
本次分享会的视频记录B站链接：https://www.bilibili.com/video/BV1yP4y1Z7qF?spm_id_from=333.999.0.0&vd_source=6afe4b8be94a864bf36064ef28580424
