### ISSUE TITLE
3.28 A First Look at Good First Issues on Github

### ISSUE THREAD

**Issue by xgdyp** [X-lab2017/open-research#12]
论文地址：https://dl.acm.org/doi/abs/10.1145/3368089.3409746
摘要：本篇论文主要对issue label中first good issue类新手向标签进行了研究，主要的研究问题有四个：
How common do projects report GFIs?

How are GFIs solved?

What factors and problems are related to the effectiveness of GFIs?

How to identify appropriate GFIs?

分享时间：3.28 20:30

**Comment by will-ww** [comment]
> 论文地址：https://dl.acm.org/doi/abs/10.1145/3368089.3409746 摘要：本篇论文主要对issue label中first good issue类新手向标签进行了研究，主要的研究问题有四个： How common do projects report GFIs?
> 
> How are GFIs solved?
> 
> What factors and problems are related to the effectiveness of GFIs?
> 
> How to identify appropriate GFIs?
> 
> 分享时间：3.28 20:30

我们能否迭代一个论文分享的模板与流程，这样我们按照一个标准化的方式进行开展与沟通，几个重要的环节包括：

- 论文选题
- 会前相关资料分享
- 论文分享、讨论、纪录
- 会后内容输出
- 后续（如果有的话）

**Comment by will-ww** [comment]
分析与输出一篇文章，还可以参考：
[templete.md](https://github.com/X-lab2017/open-research/files/8356793/templete.md)

**Comment by xgdyp** [comment]
我感觉很好，我做了一些记录，等明天讲完以后可以再把这些记录按照这种格式传上来

**Comment by will-ww** [comment]
> 我感觉很好，我做了一些记录，等明天讲完以后可以再把这些记录按照这种格式传上来

好滴，我们配合你来建立流程和模板，给大家打个样哈~

**Comment by birdflyi** [comment]
> 论文地址：https://dl.acm.org/doi/abs/10.1145/3368089.3409746 摘要：本篇论文主要对issue label中first good issue类新手向标签进行了研究，主要的研究问题有四个： How common do projects report GFIs?
> 
> How are GFIs solved?
> 
> What factors and problems are related to the effectiveness of GFIs?
> 
> How to identify appropriate GFIs?
> 
> 分享时间：3.28 20:30

可以在 [README.md](https://github.com/X-lab2017/open-research/blob/main/README.md) T18 放上  [Video] 链接~ @xgdyp
