### ISSUE TITLE
[Presentation] A method for identifying references between projects in GitHub

### ISSUE THREAD

**Issue by birdflyi** [X-lab2017/open-research#124]
### Title

A method for identifying references between projects in GitHub

### Link

https://www.sciencedirect.com/science/article/pii/S0167642322000910

### Year

2022

### Author and affiliation

Baochuan Liu a, Li Zhang a, Jing Jiang a,∗, Liang Wang b
a State Key Laboratory of Software Development Environment, Beihang University, Beijing, China
b State Key Laboratory for Novel Software Technology, Nanjing University, Jiangsu, China

### Conference or Journal

Science of Computer Programming

### Rank

SCIE

### Keywords

References identification
Redirected project
GitHub

### Selecting Reason

GitHub协作中的引用网络

**Comment by will-ww** [comment]
娄博推荐的这篇文章有不少启发，包括：
- 综述了项目 reference 关系构建的不同方法：基于源代码、基于配置文件、基于开发者交互（本文即属于该类型）、开发者共同活跃仓库（Frank 的方法）
- 给出了 reference 关系构建的意义和常用的两个方法 Reference coupling 和 Issue Units
- 给出一个简单的比较不同 reference 关系构建方法的性能，更多的边、更多的项目、更大的密度
- 还给出了一个不同方法的比较：在识别影响力项目上，IREL 的性能更好，他将 [2013 年的一篇文章](https://ieeexplore.ieee.org/document/6498480)作为基准，我们的影响力排名方法完全可以取代它这个工作；
- 还给出了 reference 关系的八种类别，虽然还没有看到这些类别有些什么具体的应用，但感觉也是可以做文章的；
- 最后，这篇文章发表的期刊 Science of Computer Programming，也是 CCF B 类的，总之，可以借鉴的工作和方法不少~

论文中所使用到的代码：https://github.com/IREL-OSS/SCP2022
