### ISSUE TITLE
[Presentation] ASK-RoBERTa: A pretraining model for aspect-based sentiment classification via sentiment knowledge mining

### ISSUE THREAD

**Issue by PureNatural** [X-lab2017/open-research#128]
### Title

ASK-RoBERTa: A pretraining model for aspect-based sentiment classification via sentiment knowledge mining

### Link

https://www.sciencedirect.com/science/article/abs/pii/S0950705122007584

### Year

2022

### Author and affiliation

Lan You a,b, Fanyu Han a,b, Jiaheng Peng a,b, Hong Jin a,b,* Christophe Claramunt c
a School of Computer Science and Information Engineering, Hubei University, Hubei Wuhan, 430062, China
b Engineering Research Center of Hubei Province in Intelligent Government Affairs and Application, of Artificial Intelligence, Hubei Wuhan, 430062, China
c Naval Academy Research Institute, Brest, 29240, France

### Conference or Journal

Knowledge-Based Systems

### Rank

SCIE

### Keywords

Aspect-based sentiment classification
RoBERTa
Sentiment knowledge
Dependency grammar
Knowledge mining

### Selecting Reason

情感分析任务可同样适用于Github的评论文本中。

**Comment by will-ww** [comment]
> Is Developer Sentiment Related to Software Bugs: An Exploratory Study on GitHub Commits（地址：[https://www.researchgate.net/publication/340401339_Is_Developer_Sentiment_Related_to_Software_Bugs_An_Exploratory_Study_on_GitHub_Commits）](https://www.researchgate.net/publication/340401339_Is_Developer_Sentiment_Related_to_Software_Bugs_An_Exploratory_Study_on_GitHub_Commits%EF%BC%89)
> 
> 关于Github里commit信息的研究，蛮有意思的，大家感兴趣的可以读一下。

好咧，可以加到我们的论文库中~ @bifenglin

**Comment by will-ww** [comment]
看了下，用 Google Scholar 去搜索这篇文章，还是有不少相关方面的研究，值得好好借鉴下：https://scholar.google.com/scholar?cites=978090304120250617&as_sdt=2005&sciodt=0,5&hl=zh-CN

**Comment by K-Bion** [comment]
有上传代码吗

**Comment by K-Bion** [comment]
> Is Developer Sentiment Related to Software Bugs: An Exploratory Study on GitHub Commits（地址：[https://www.researchgate.net/publication/340401339_Is_Developer_Sentiment_Related_to_Software_Bugs_An_Exploratory_Study_on_GitHub_Commits）](https://www.researchgate.net/publication/340401339_Is_Developer_Sentiment_Related_to_Software_Bugs_An_Exploratory_Study_on_GitHub_Commits%EF%BC%89)
> 
> 关于Github里commit信息的研究，蛮有意思的，大家感兴趣的可以读一下。

ASK-RoBERTa: A pretraining model for aspect-based sentiment classification via sentiment knowledge mining
Does this article have an upload code？
