### ISSUE TITLE
[Attention] ICSE 2022 Technical Track Distinguished Papers  

### ISSUE THREAD

**Issue by xiaoya-yaya** [X-lab2017/open-research#136]
### Description

![FSfe-M2UcAIfz4z](https://user-images.githubusercontent.com/56542972/198006196-96561b44-d862-48f3-9664-65558d557179.jpeg)

最顶级会议的最佳论文，大家可以关注，最新的研究动向～

**Comment by tyn1998** [comment]
抢占一篇，未来几周周一例会分享~

[What Makes a Good Commit Message?](https://arxiv.org/abs/2202.02974)

**Comment by xiaoya-yaya** [comment]
我感觉近几年 qualitative analysis 真的很受软工顶会青睐，话题也很多围绕开源社区与在线协作

比如说这两篇都是 CMU 的：

- [“Did You Miss My Comment or What?” Understanding Toxicity in Open Source Discussions](https://www.cs.cmu.edu/afs/cs.cmu.edu/Web/People/ckaestne/pdf/icse22_toxicity.pdf)

- [Collaboration Challenges in Building ML-Enabled Systems: Communication, Documentation, Engineering, and Process](http://www.cs.cmu.edu/~ckaestne/pdf/icse22_seai.pdf)

**Comment by will-ww** [comment]
确实，数据开放性、技术手段等都提升了，当然，本身这方面的论文也还是不少的，还是有很多以前都没怎么看到过的方向~
