### ISSUE TITLE
[Presentation] What Makes a Good Commit Message?

### ISSUE THREAD

**Issue by tyn1998** [X-lab2017/open-research#138]
### Title

What Makes a Good Commit Message?

### Link

https://dl.acm.org/doi/10.1145/3510003.3510205

### Year

2022

### Author and affiliation

Yingchen Tian, Beijing Institute of Technology Beijing, China, tianyc10@foxmail.com
Yuxia Zhang, Beijing Institute of Technology Beijing, China, yuxiazh@bit.edu.cn
Klaas-Jan Stol, University College Cork and Lero School of Computer Science and IT Cork, Ireland, k.stol@ucc.ie
Lin Jiang, Beijing Institute of Technology Beijing, China, jianglin17@bit.edu.cn
Hui Liu, Beijing Institute of Technology Beijing, China, liuhui08@bit.edu.cn

### Conference or Journal

[ICSE '22: Proceedings of the 44th International Conference on Software Engineering](https://dl.acm.org/doi/proceedings/10.1145/3510003)

### Rank

A

### Keywords

Commit-based software development, open collaboration, commit message quality

### Selecting Reason

Everyone should know how to write a GOOD commit message!

### Supplementary

N.A.

**Comment by tyn1998** [comment]
论文分享结束，感谢大家的聆听~

现在有个资料整理的问题，请问我应该把PPT放到我们语雀的哪个知识库的哪个目录中？

<img width="1282" alt="image" src="https://user-images.githubusercontent.com/32434520/201683015-aaac1992-645d-4e24-a1d3-d2cec099becb.png">

**Comment by birdflyi** [comment]
推荐x-publication，see #144

**Comment by birdflyi** [comment]
居然又有个x-talk，不过以前的都是放在x-publication中的

**Comment by tyn1998** [comment]
已归档：

- 论文pdf位置：https://xlab2017.yuque.com/msdpvs/dtg7ew/29898001
- ppt位置：https://xlab2017.yuque.com/msdpvs/dtg7ew/29898010
