### ISSUE TITLE
Some pictures and text in the paper 《What Makes a Great Maintainer of Open Source Projects》are too blury

### ISSUE THREAD

**Issue by zhicheng-ning** [X-lab2017/open-research#15]
![image](https://user-images.githubusercontent.com/39022409/160408277-dafd9b78-8d12-4e1a-92e2-03dbda50deb0.png)
![image](https://user-images.githubusercontent.com/39022409/160408797-655d46e5-51ec-44d8-b79f-a610f72e563f.png)

Some pictures and text in the paper 《What Makes a Great Maintainer of Open Source Projects》 are too blurry.

**Comment by birdflyi** [comment]
The PDF links need to be fixed.

**Comment by zhicheng-ning** [comment]
> The PDF links need to be fixed.

done!
