### ISSUE TITLE
[CFP] ESEC/FSE 论文投稿促进贴 

### ISSUE THREAD

**Issue by will-ww** [X-lab2017/open-research#163]
### Description

和其他软件工程的顶会一样，[ESEC/FSE 2023](https://2023.esec-fse.org/) 有着非常丰富的投稿 track，大部分的截至时间都是在 4、5 月份，应该够用。除了 Research Papers | Industry Papers 以外，重点再推荐几个：
- [Demonstrations](https://2023.esec-fse.org/track/fse-2023-demonstrations)：Demo 是软工类非常常见的类型，一般是 4 页 内容，实验室的 Hypercrx、OpenGalaxy、OpenDashboard 等都是非常适合的；
- [Ideas, Visions and Reflections](https://2023.esec-fse.org/track/fse-2023-ideas--visions-and-reflections)：是一类创新型的前瞻性论文，有点像开题报告，同样不超过 4 页内容；

大家可以热烈讨论~

前面和商量后，目前有如下几篇潜在的投稿论文：

- [ ] Industry Papers (Thu 18 May): **OpenRank & 开源激励 & Network perspective** @xiaoya-yaya @frank-zsy 
- [ ] Demonstrations (Thu 11 May): **Hypercrx** @tyn1998 
- [ ] Demonstrations (Thu 11 May): **OpenGalaxy** @longyanz
- [ ] Demonstrations (Thu 11 May): **OpenLeaderboard+ OpenDashboard** @zhicheng-ning 
- [ ] Ideas, Visions and Reflections (Wed 3 May 2023): **OpenDigger @ OpenRank** @frank-zsy @will-ww @xgdyp 

大家可以补充与调整~

**Comment by will-ww** [comment]
前面和商量后，目前有如下几篇潜在的投稿论文：

- [ ] Industry Papers (Thu 18 May): **OpenRank & 开源激励 & Network perspective** @xiaoya-yaya @frank-zsy 
- [ ] Demonstrations (Thu 11 May): **Hypercrx** @tyn1998 
- [ ] Demonstrations (Thu 11 May): **OpenGalaxy** @longyanz
- [ ] Demonstrations (Thu 11 May): **OpenLeaderboard+ OpenDashboard** @zhicheng-ning 
- [ ] Ideas, Visions and Reflections (Wed 3 May 2023): **OpenDigger @ OpenRank** @frank-zsy @will-ww @xgdyp 

大家可以补充与调整~

**Comment by tyn1998** [comment]
借了个号，把ESEC/FSE 2021和2022能下的Accepted都下了，已上传到语雀~

- [ESEC/FSE 2021](https://xlab2017.yuque.com/g/msdpvs/dtg7ew/folder/30757405)
- [ESEC/FSE 2022](https://xlab2017.yuque.com/g/msdpvs/dtg7ew/folder/30757416)

<img width="1207" alt="image" src="https://user-images.githubusercontent.com/32434520/233823116-646004e8-851f-45c2-83d1-8b51d18a6751.png">

**Comment by xiaoya-yaya** [comment]
找到了 [FSE2021 ](https://2021.esec-fse.org/)各个 Track 的接受率，给大家增加点信心，demo track 接收率非常高

<img width="500" alt="image" src="https://user-images.githubusercontent.com/56542972/234160120-da3c3190-c830-47d8-9ec5-ff9da0241a71.png">
