### ISSUE TITLE
[CFP] 计算机研究与发展 | 数据驱动的信息系统服务 

### ISSUE THREAD

**Issue by will-ww** [X-lab2017/open-research#166]
### Description

随着新一轮科技革命与产业变革的深入发展，以互联网为代表的新型信息技术正在深刻地改变社会各领域，数据作为关键生产要素的价值日益凸显，信息化被赋予新的内涵。为加速传统产业向智能化、绿色化、融合化方向转型升级，亟需利用新型信息技术提供数字化服务，数据是促成这一转型新的动力能源（New Power）。当前，我们正处在数字化转型的关键时期，支撑各行业信息系统精准服务的数据需求日趋多元。

为了推动我国学者在数据驱动的信息系统领域相关研究，及时报道最新的研究成果，《计算机研究与发展》联合CCF信息系统专委会将于2024年中出版专题——数据驱动的信息系统服务，本专题将聚焦数据驱动的信息系统在提供精准服务过程中产生的新方法和新技术，围绕信息系统的两个重要组成：数据与服务，为相关研究者和实践者提供集中发表最新成果的平台。欢迎相关研究领域的专家学者、科研人员踊跃投稿。此外，专题将与第二十届CCF中国信息系统及应用大会（WISA2023）合作，所有拟录用稿件均需在WISA2023专题论坛上报告交流。

征文范围（包括但不限于以下主题）

1. 数据驱动信息系统服务的体系架构
2. 数据驱动信息系统服务的知识推理与问答
3. 数据驱动信息系统服务的推荐与决策
4. 数据驱动信息系统服务的安全与隐私
5. 数据驱动信息系统服务的交互技术
6. 数据驱动信息系统服务的标准化测试方法
7. 数据驱动信息系统服务的智能化运维
8. 数据驱动信息系统服务的领域应用
9. 面向信息系统的数据新能源全生命周期管理
10. 异构硬件环境下的信息系统服务
11. 基于分布式集群或云环境的信息系统服务
12. 面向信息系统服务的数据治理
13. 信息系统服务中的安全保护
14. 数据驱动的新型信息系统服务

时间节点：
- 征文截止日期：2023年7月30日
- 评审结束日期：2023年8月20日
- 修改稿提交日期：2023年8月31日
- 预录用结果发出日期：2023年9月5日
- WISA会议报告日期：2023年9月15-17日
- 最终稿提交日期：2023年10月31日
- 计划出版日期：2024年中

详细信息：[点击这里](https://mp.weixin.qq.com/s/tuf17MeM-71n0VoWeM2hNg)

**Comment by will-ww** [comment]
几个候选方向可以考虑：

1. 数据驱动的开源发展生态学：测量、评价、激励与发展

2. OpenDigger：面向开源社区健康可持续发展的评价与激励工具

3. OpenRank：数据驱动的开源社区贡献度评价与激励方法

**Comment by will-ww** [comment]
> 几个候选方向可以考虑：
> 
> 1. 数据驱动的开源发展生态学：测量、评价、激励与发展
> 2. OpenDigger：面向开源社区健康可持续发展的评价与激励工具
> 3. OpenRank：数据驱动的开源社区贡献度评价与激励方法

和夏博士商量后，确定选 3 OpenRank 作为投稿方向。因此，咱们可以做个如下分工：

候选题目：
- OpenRank：数据驱动的开源社区贡献度评价与激励方法
- OpenRank：基于开发者协作行为数据的开源社区贡献度计算方法
- 基于开发者行为数据的开源社区贡献度评价与激励服务

**Comment by xiaoya-yaya** [comment]
简单写了一个摘要，并做了下分工，大家看一看是否有问题，我们6月8号（下周四）整合一版初稿 @will-ww @frank-zsy 

1. 研究背景（夏小雅+王老师）
2. 相关工作（夏小雅）
3. 开发者协作些微数据采集与服务
    3.1 GitHub 开发者协作行为数据采集（韩凡宇）
    3.2 OpenDigger：数据驱动的开源生态数据服务与分析（Frank）
4. 开发者贡献度评价（Frank）
    4.1 OpenRank：基于协作网络的开发者贡献度评价算法
    4.2 收敛性证明
5. 激励服务及有效性验证
    5.1 XSOSI 激励服务（王老师）
    5.2 基于RDD和开发者访谈的有效性验证（夏小雅）
6. 结论

**Comment by xiaoya-yaya** [comment]
[基于开发者行为数据的开源社区贡献度评价与激励服务.docx](https://github.com/X-lab2017/open-research/files/11634302/default.docx)

**Comment by will-ww** [comment]
[oss101 ](https://github.com/X-lab2017/oss101)也是个不错的案例：

![image](https://github.com/X-lab2017/open-research/assets/15010826/1ad00d4d-f693-4b52-be91-a63088d86601)

![image](https://github.com/X-lab2017/open-research/assets/15010826/e4674e8e-b37c-4248-8e7f-c726da696e8f)

![image](https://github.com/X-lab2017/open-research/assets/15010826/896984c2-e687-4147-8583-48d93f917361)

**Comment by will-ww** [comment]
已延期，具体参见：https://mp.weixin.qq.com/s/ggeEvnVaA2-HCg1xuZAwKg

**Comment by xiaoya-yaya** [comment]
时间节点追踪：
<img width="720" alt="image" src="https://github.com/X-lab2017/open-research/assets/56542972/ab637df2-5676-49b7-9cd4-69281769764e">

**Comment by will-ww** [comment]
在各位同学的大力支持下，本次 WISA 研发专刊驱动了实验室两篇中文论文的整理，也成为同学们后续研究方向和成果产出的指导性框架，现以技术报告的形式发出来，供大家参考~ @X-lab2017/x-lab 


[Opendigger - 技术报告.pdf](https://github.com/X-lab2017/open-research/files/12237903/Opendigger.-.pdf)
[OpenPerf - 技术报告.pdf](https://github.com/X-lab2017/open-research/files/12237907/OpenPerf.-.pdf)
