### ISSUE TITLE
[WISA 2023] 截稿日期延至5月22日

### ISSUE THREAD

**Issue by will-ww** [X-lab2017/open-research#174]
### Description

由中国计算机学会（CCF）主办、CCF信息系统专业委员会和四川大学计算机学院（软件学院  智能科学与技术学院）共同承办的旗舰会议——第二十届CCF中国信息系统及应用大会（WISA 2023）（会议编号：CCF-TC-23-077）将于2023年9月15-17日在四川成都召开。

大会将围绕“数智共生与信息系统”主题，关注数智共生、智慧信息系统、数字化转型与信息系统安全等领域，聚焦元宇宙、知识图谱、区块链等关键问题，搭建学术、企业、政府交流平台。会议将邀请信息系统关键技术领域的资深专家做主题报告，分享最新的前沿技术与产业热点。会议期间，还将组织专题论坛、企业前沿论坛、专委沙龙等活动，力求全方位地扩大交流范畴，拓展交流形式，提升交流效果。

大会同时接收中文、英文投稿。为确保所录用论文的质量及水平，程序委员会将对所投稿件组织严格的同行专家评议审稿，所有录用论文均要求参会交流。所录用中文论文将推荐到 《计算机学报》《计算机研究与发展》《计算机科学与探索》《小型微型计算机系统》《计算机科学》《计算机工程与应用》《计算机工程》《计算机应用》《计算机与数字工程》等中文期刊发表（须再次审稿）。所录用英文论文将由斯普林格出版社（Springer）以LNCS系列出版会议论文集（WISA2019、WISA 2020、WISA2021和WISA2022论文集全部论文均被EI收录）。

大会热忱欢迎从事信息系统及相关领域的专家、学者、学生和专业技术人员踊跃投稿和与会交流。

WISA 2023的征文主题包括（但不限于）：
- 信息系统体系架构
- 信息系统数据融合
- 信息系统数据挖掘
- 信息系统存储管理
- 信息系统查询处理
- 信息系统检索技术
- 信息系统安全与防护
- 信息系统可视化技术
- 信息系统数字化转型
- 大数据与信息系统
- 知识图谱与信息系统
- 区块链与信息系统
- 机器学习与信息系统
- 智能决策与信息系统
- 推荐系统与信息系统
- 信息系统自然语言处理
- 智慧教育与教学系统
- 智慧健康与医疗系统

会议网站：https://conf.ccf.org.cn/wisa2023

投稿信息

（1）会议投稿网址：

https://cmt3.research.microsoft.com/WISA2023

（2）格式与要求：

中文论文格式采用《计算机工程与应用》投稿模板，论文长度要求不超过7页：

http://cea.ceaj.org/CN/column/column18.shtml

英文论文格式采用Springer LNCS模板，论文长度要求不超过12页：
https://www.springer.com/cn/computer-science/lncs/conference-proceedings-guidelines

（3） 论文应是未发表的研究成果（且未同时提交给其他刊物或会议评审），应包括中英文题目、中英文摘要、关键词、正文和参考文献等。

（4）论文投稿与审稿采取双盲评审。

**重要日期**

摘要提交：2023年5月22日 (23:59, 北京时间)

全文提交：2023年5月22日 (23:59, 北京时间)

审稿结果：2023年7月3日

正式版本提交：2023年7月17日

会议日期：2023年9月15-17日

**Comment by will-ww** [comment]
陈可璇同学的论文《基于用户反馈数据的产品质量分析研究与实践》已被该会议录用~

以及我们 9 月 16 日在该会议上，有一个开源教育的论坛，敬请期待~

**Comment by YuZekai** [comment]
![D0358722E6C7469D72DE3F0DBC123DD3](https://github.com/user-attachments/assets/4fdef58b-f08d-4f7d-a80e-87e5e6240067)
这是什么情况？？？

**Comment by will-ww** [comment]
这个确实非常奇怪，这个 Issue 在去年已经关闭了，为啥会有这种清苦~ :-)

**Comment by YuZekai** [comment]
那应该是当时GitHub发错的吧，我看邮件是23年7月26的，昨天才看到它 X﹏X

**Comment by zhingoll** [comment]
> 为什么会@我
![image](https://github.com/user-attachments/assets/3f987510-df67-40d3-a35c-d3a07ee5874d)

是当时不小心选错了，所以您当时会收到被“mentioned”的邮件信息 ，抱歉打扰了😅~

**Comment by YuZekai** [comment]
> > 为什么会@我
> > ![image](https://private-user-images.githubusercontent.com/113612424/386423252-3f987510-df67-40d3-a35c-d3a07ee5874d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE2NDc5MjMsIm5iZiI6MTczMTY0NzYyMywicGF0aCI6Ii8xMTM2MTI0MjQvMzg2NDIzMjUyLTNmOTg3NTEwLWRmNjctNDBkMy1hMzVjLWQzYTA3ZWU1ODc0ZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExNVQwNTEzNDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01ZGEzYjM0MWM5MDM5NTMzZjhiYzA3NTNlM2JkM2JhOWY3NWMyMDQxNDc2MWU5OTkwYmEyYTEyZjhkOWUyODBiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.fbZeNLTNJsIXKSJ1-WLDN0Wp0XK3NIJV0zLc45C27B0)
> 
> 是当时不小心选错了，所以您当时会收到被“mentioned”的邮件信息 ，抱歉打扰了😅~

okok,没事，只是感觉好神奇🤣
