### ISSUE TITLE
[开题框架] 基于 WebGPU 和力导向布局的开源协作网络可视化研究

### ISSUE THREAD

**Issue by tyn1998** [X-lab2017/open-research#175]
开题报告请见：https://xlab2017.yuque.com/ukybhe/gmmbf2/ms9dw7wgmgwzu4e6

**Comment by pomelo-nwu** [comment]
> 关于动态网络图，在视觉上的连续性，以下是我四年前写的一些思考，希望对你有帮助

我们站在用户的角度思考整个动态网络分析流程

分析前：用户期待的是扩散节点的位置可预测，大致这掉它在哪个位置展示
分析中：用户期待整个过程稳定可持续，不丢失上下文
分析后：用户期待可回溯，因为整个分析过程都在重复 价值节点 到 价值子网 再到 目标节点的循环分析中。
 

拆解到技术方案。首先这是一个布局问题，布局分为稳定性布局和非稳定性布局

![image](https://github.com/X-lab2017/open-research/assets/10703060/74185403-aabb-424d-9bc8-7ad68a4ba297)

我们先来单看稳定性布局，顾名思义，同样的节点输入，有着同样的布局位置。有点类似JS编程中纯函数的概念。

因此它在分析前是很好预测的，比如circlar布局，新增的节点，一定也在这个环上。
对于可持续问题，只要通过扩散前和扩散后的坐标进行补间动画即可。
最后的可回溯问题，是个通用的工程解法，做个todo/redo功能即可。
 

麻烦的是非稳定性布局，比如力导。

所有的节点，每次布局，位置都受力随机发生改变，不可预测
对于单个节点，每次迭代的tick里，位置都发生改变，很难位置在一个固定的区间内，持续性很难做
这也是为什么大家都公认，力导算法不适合 需要持续布局的业务场景。而我们要解决的就是这个难点。

 
挑战解法：基于能量优化的力导渐进分析布局

首先我们改变思路，将全局渲染改变为局部渲染，通过diff计 算出 前一次扩散布局(PreGraph) 和 下一次扩散布局(NextGraph) 哪些节点是新增的。然后通过tweak算法，将新增的节点防止在扩散节点的方形空间里。从而解决了可预测性问题。

![image](https://github.com/X-lab2017/open-research/assets/10703060/84e980bb-768b-439e-b42e-41f458208e7e)


聚集在扩散节点周围的节点，应该让它受力撑开，比如 B 节点，而且在这个撑开的过程中，保持整个布局稳定，可持续，这里面我们就采用了自研力导，采用能量约束的方式，解决这个问题

![image](https://github.com/X-lab2017/open-research/assets/10703060/91311eac-f09f-4137-bd73-749b2c2ee8fd)

首先我们单看节点，期待节点都尽可能稳定，通过 deltaS 的位移计算公式可知，我们动态增加节点的质量，就可以让 deltaS 尽可能减小，从而达到视觉上稳定的效果，同时根据 deltaE的损耗能量公式可知，这样系统的能量递减也会加速，加快迭代稳定。
然后看整个系统的能量。我们抽取系统中最重要的 弹簧能量与库伦能量。如果 deltaSpring 为0，整个系统的能量也会减小，而这里面的优化空间，就是将固定写死的弹簧初始长度S，改为可以动态函数计算的，让它与A、B两个点的向量计算出的欧拉距离相等，从而使得相减为0。反应在图上就是A-B两节点的弹簧长度就是扩散出去的空间距离，弹簧没有发生形变，快速稳定，不会出现来回震荡的效果。
 

看下最后的算法优化效果：
![image](https://github.com/X-lab2017/open-research/assets/10703060/db12d926-c29f-4cb6-980f-fc5bd46eb55c)

**Comment by pomelo-nwu** [comment]
另外高性能计算和并行计算，G6这边也有一些输入：

- GPU 布局：https://github.com/antvis/layout/tree/v5/packages/layout-gpu/src
- Rust 布局：https://github.com/antvis/layout/tree/v5/packages/layout-rust/src
 可以尝试下 把 CPU计算的 dagre 算法改为 rust 或者 并行计算的，也是非常好的

基于力导的约束计算或者优化，学术界太多了，反倒是工业界，最关心的布局算法其实是有向分层。dagre 的布局约束或者分组再做分层布局，都是非常值得研究的点。

**Comment by tyn1998** [comment]
非常感谢 @pomelo-nwu ！！我会仔细阅读参考的~

**Comment by tyn1998** [comment]
@will-ww 王老师请帮忙看看框架图~

<img width="811" alt="image" src="https://github.com/X-lab2017/open-research/assets/32434520/353fb54b-d5c5-4486-8bff-71700eb7e939">

**Comment by will-ww** [comment]
几个觉得需要修改与优化的点包括：

- 题目肯定太长，精简下，如，**基于 WebGPU 力导向布局的动态协作网络可视化方法研究**
- 选题来源，第二个框：个人兴趣爱好
- 问题的提出：企业如何直观获取旗下开源社区整体高纬结构信息、开发者如何从宏观与微观观察开源社区的演化
- 选题意义：协作网络可视化、动态过程可视化、图可视化新方法
- 研究内容：三个内容感觉不错
- 研究方法：换一个“工程实践”
- 技术路线：内容都可以，如何逻辑性的组织下，包括文字内容，正文中也可以再通过详细的步骤或图展示
- 实验设计：这个课题的实验，比较适合用性能指标来做，例如三维布局算法，时间、网络传输等方面的性能对比提升；不用像数据科学类型的论文的做法，工程效果是本论文优先关注的地方。
- 感觉挺好！

**Comment by tyn1998** [comment]
@will-ww 感谢王老师的建议！修改后的框架图如下：

<img width="815" alt="image" src="https://github.com/X-lab2017/open-research/assets/32434520/01ae8121-be7b-47fd-8386-a0167c4e4152">

我基于王老师关于标题的建议拟定了一个新的更简短的标题《基于 WebGPU 和力导向布局的 开源协作网络可视化方法研究》。

**Comment by tyn1998** [comment]
行动起来，为我的毕设项目创建了一个仓库：https://github.com/tyn1998/master-project-2024

欢迎大家 @X-lab2017/x-lab  在我的仓库中讨论、建议、指导~
