### ISSUE TITLE
[Presentation] Activity-Based Analysis of Open Source Software Contributors: Roles and Dynamics

### ISSUE THREAD

**Issue by xgdyp** [X-lab2017/open-research#182]
### Title

Activity-Based Analysis of Open Source Software Contributors: Roles and Dynamics

### Link

https://ieeexplore.ieee.org/abstract/document/8817054/

### Year

2019

### Author and affiliation

[Jinghui Cheng](https://ieeexplore.ieee.org/author/37086054191)
Department of Computer and Software Engineering, Polytechnique Montreal, Montreal, Canada
[Jin L.C. Guo](https://ieeexplore.ieee.org/author/37086462748)
School of Computer Science, McGill University, Montreal, Canada

### Conference or Journal

ICSE Workshop on Cooperative and Human Aspects on Software Engineering, CHASE

### Rank

A

### Keywords

source software, open source community, activity-based analysis, contributor roles

### Selecting Reason

research for community role

**Comment by birdflyi** [comment]
I collected some Interesting Perspectives on Building Networks:
1. [Knowledge](https://www.bilibili.com/video/BV1rM411N7RQ/?vd_source=a5d1ea6cfc182e156535500aaeae4f6e#:~:text=%E8%A7%86%E8%A7%92%EF%BC%9AKnowledge%20Network-,00%3A34%3A30,-1%E5%88%86%E9%92%9F%E5%89%8D) and [Reference](https://www.sciencedirect.com/science/article/abs/pii/S0950584919300527), e.g. Reference Coupling.
2. [Contribution](https://dl.acm.org/doi/abs/10.1145/512035.512055) and Collaboration, e.g. [Role](https://www.bilibili.com/video/BV1nc411G7XM/?vd_source=a5d1ea6cfc182e156535500aaeae4f6e#:~:text=Based%20Software%20Development%3A-,00%3A03%3A30,-%E5%88%9A%E5%88%9A) and Community Structure.
3. [Dependency](https://dl.acm.org/doi/abs/10.1145/3183440.3183454) and Supply, e.g.  R CRAN(Chapter 5.1 of Constructing supply chains in open source software), npm supply chain.

**Comment by will-ww** [comment]
补充：[Map of GitHub（2D 形态）](https://github.com/anvaka/map-of-github) 项目是一个用 Stargazing 关系进行构建网络的，也不错~
