### ISSUE TITLE
将暑假两篇技术报告成果转化为英文期刊论文

### ISSUE THREAD

**Issue by will-ww** [X-lab2017/open-research#219]
### Description

随着[暑期数据驱动的信息系统服务专刊](https://github.com/X-lab2017/open-research/issues/166)的启动，最后形成了完整的[两篇技术报告](https://github.com/X-lab2017/open-research/issues/166#issuecomment-1661748775)，较好的总结了实验室前面的成果。

在此基础之上，提议将两篇技术报告进行适当的修订与更新后，投两个期刊已完成实验室成果的沉淀与影响力主张。

目标期刊如下：

- [**BenchCouncil Transactions on Benchmarks, Standards and Evaluations**](https://www.sciencedirect.com/journal/benchcouncil-transactions-on-benchmarks-standards-and-evaluations)：作为 position paper 较好的收录地，非常适合 OpenPerf；同时，学院作为 [BenchCouncil](https://www.benchcouncil.org/cn/cn.html) 的一员，自然也倾向于投稿该期刊，适合作为实验室基础性研究工作，但作为博士论文的支撑工作不明显；
- [**Data Science and Engineering**](https://www.springer.com/journal/41019)：另一本学院主张所共同支持发展的期刊，因此将 OpenDigger 的 position paper 发到该期刊上面具有一定的价值与意义，同样适合作为实验室基础性研究工作，但作为博士论文的支撑工作不明显。

欢迎各位同学牵头并积极参加上述两篇论文的撰写与发表工作~

**Comment by xiaoya-yaya** [comment]
由 @Zzzzzhuzhiwei 同学牵头，将暑期整理的 [Opendigger - 技术报告.pdf](https://github.com/X-lab2017/open-research/files/12237903/Opendigger.-.pdf) 转化为英文学术论文，投稿到
[Data Science and Engineering](https://www.springer.com/journal/41019) 期刊上，相关进展可以在此issue下跟进～
