### ISSUE TITLE
[CFP] OSSLab 工作成果介绍与 X-lab 论文投稿促进

### ISSUE THREAD

**Issue by xiaoya-yaya** [X-lab2017/open-research#229]
## Description
2023 年 10/21～22，[CCF中国开源软件大会](https://mp.weixin.qq.com/s/JjhdrqNzJiFAaxEWhomokA)顺利召开，也是第一届线下会议成功举办，学术界与产业界的众多巨斗和大咖齐聚长沙。对于开源软件生态的研究，北京大学周明辉老师带领的 [OSSLab](https://osslab-pku.org/people/) 有非常深厚的学术成果积累，我们之前的组会上也分享了许多他们的文章，OSSLab的研究模式、思路、方法很值得我们参考与借鉴。

这篇帖子意在：

- 介绍学术同行 OSSLab 的研究方向和成果，供同学们了解学习，在后续持续交流的基础上展开合作；
- 同时接棒王老师在暑期前的 [Call For Paper](https://github.com/X-lab2017/open-research/issues/220)，介绍下半年 ICSE 系列会议值得关注和投稿的 Track，大家分工和聚力，争取在明年葡萄牙里斯本和更多软工大佬们进行交流～

![IMG_4272](https://github.com/X-lab2017/open-research/assets/56542972/2797e754-1b48-470a-8f03-63efd9c63e87)

**Comment by xiaoya-yaya** [comment]
## OSSLab：Open Source Software Data Analytics Lab
### 官网
https://osslab-pku.org/

### 介绍
我们是北京大学计算机学院的一个研究小组。从广义上讲，我们的研究属于**软件工程**领域，其重点是**提高软件开发的效率和质量**。为实现这一目标，软件工程领域的研究方法多种多样。我们经常采用**经验主义的方法**，通过**观察**现实生活中的事物，总结经验做法，从而建立理论和机制。我们经常发明智能技术和机器人，帮助控制复杂系统及其开发。
更具体地说，我们目前的工作重点是观察软件仓库，衡量开发人员的生活方式（pattern），以达到各种目的，如帮助理解和控制大型复杂软件系统、社会和世界。根据我们要解决的具体问题，我们可能会使用**多种技术**和**跨学科方法**。

### 研究 Topics

- 开源供应链: Open Source Software Supply Chain (modeling, risk analysis and resolution)
- 开源生态复杂系统：Characterizing open source ecosystem as a complex system
- 开源许可证：Open source license compatibility detection and conflict resolution
- 开源可持续性：Open Source Sustainability (deprecation prediction)
- 开发者画像：Profiling Developer (expertise, personality and learning trajectory)
- 软件工程机器人：Software engineering bots (library migration recommender/GFI recommender/dependency update bot/release note bot)

### 代表成员与代表作
* [Yuxia Zhang](https://sites.google.com/view/yuxia-zhang/):[ICSE'20] **How do Companies Collaborate in Open Source Ecosystems? An Empirical Study of OpenStack.** 
* [Xin Tan](https://sites.google.com/view/xintan/):(FSE'20] **A First Look at Good First Issues on GitHub.**
* [Hao He](https://hehao98.github.io/): [FSE'21] **A Large-Scale Empirical Study on Java Library Migrations: Prevalence, Trends, and Rationales**
* [Wenxin Xiao](https://osslab-pku.org/publications/): [FSE'23]**How Early Participation Determines Long-Term Sustained Activity in GitHub Projects?**



### 工具
https://osslab-pku.org/projects/
<img width="595" alt="image" src="https://github.com/X-lab2017/open-research/assets/56542972/97b08251-9fe4-481f-af4e-37d943740350">

**Comment by xiaoya-yaya** [comment]
## 10月-12月 ICSE'24 及系列会议投稿促进
<img width="1467" alt="image" src="https://github.com/X-lab2017/open-research/assets/56542972/178793ae-eeb7-4d15-be58-668e17449486">

## 基本信息

- 举办时间：2024年4月14日-4月20日
- 举办地点：葡萄牙里斯本
- 更多详见官网：https://conf.researchr.org/home/icse-2024

## 值得关注的Track
### 1. [SEIP](https://conf.researchr.org/track/icse-2024/icse-2024-software-engineering-in-practice)（已截止，ddl 10/6)
* 投稿形式：非盲审；10页/2页
* 论坛介绍：**从业者**和研究人员探讨具体软件工程问题的见解、创新和解决方案，以解决直接影响实践的软件工程研究。SEIP将吸引**工业**和学术界的参与者和演讲者，该领域将由邀请演讲、论文展示和互动会议组成，所有活动都将重点关注**软件实践**。
* 已投稿文章：**Motivating Open Source Contributions through Social Network Evaluation: A Gamification Practice from Alibaba** @frank-zsy @xiaoya-yaya 

### 2. [Doctoral Symposium](https://conf.researchr.org/track/icse-2024/icse-2024-doctoral-symposium)
* DDL：11月22号
* 投稿形式：2页（Early PhD）/4页（Late PhD）；非盲审；类开题；由导师提供推荐信
* 论坛介绍：研讨会的目的是给博士生提供当前和未来的研究方向的建设性反馈意见。早期博士以2页的摘要介绍他们已经确定的研究领域，概述博士论文的主题，学生将应邀在研讨会上展示海报，并有机会向与会者发表简短演讲；晚期博士以4页的文章展示已有的成果，应邀在研讨会上展示海报，并向与会者和咨询委员会发表演讲。
* 干系人：@xiaoya-yaya, @bifenglin, @frank-zsy, @PureNatural, @birdflyi 

### 3. [ACM Student Research Competition](https://conf.researchr.org/track/icse-2024/icse-2024-SRC)
* DDL：11月16号
* 投稿形式：2-page research abstract describing a research problem, its background and related work, the proposed solution and its novelty, the actual results, and your contributions
* 干系人：@博士具备初步成果的ideas；@研三的开题

## 值得关注的系列会议
### ICPC（CCF-B）
链接：https://conf.researchr.org/home/icpc-2024
1. Research Track：ddl 11月3日。
- [ ] 开源软件项目供应链可维护性 @bifenglin 
2. Tool Demo: ddl 12月1日。
- [ ] Hypercrx @tyn1998 ; 
- [ ] OpenGalaxy @longyanz 
3.  EAR:ddl  11月22日。(只需要介绍 Research in progress,  不需要评估结果，但需要idea新颖) 
- [ ] 复杂引用网络 @birdflyi ；
- [ ] 大模型的幻觉问题等 @bifenglin 

### 3. MSR（CCF-C）
链接：https://2024.msrconf.org/
1. Technical Paper：11月20日。
- [ ] 文本识别与分类 @PureNatural 
2. Data and Tool：12月8日。
- [ ] 开放原子大赛中的代表数据集、挖掘与洞察结果展示 @研二/研一
- [ ] OSGraph data showcase @xiaoya-yaya 

### 值得关注的Workshops
链接：https://conf.researchr.org/track/icse-2024/icse-2024-workshops

### 另：期刊投稿
- [ ] 详见 #219，将OpenDigger技术报告转化为英文期刊论文 @Zzzzzhuzhiwei

**Comment by will-ww** [comment]
> ## OSSLab：Open Source Software Data Analytics Lab
> ### 官网
> https://osslab-pku.org/
> 

前面也整理了下周老师实验室的论文集，供大家参考与系统阅读：https://xlab2017.yuque.com/msdpvs/fzem1h/32741796

**Comment by bifenglin** [comment]
目前规划：
《Uncover the Risks of Outdated Third-Party Components in Software Supply Chains: Insights from the NPM Ecosystem》-ICPC
《Assessing Maintainability Risks in the Open Source Software Supply Chain: A Novel Quality Model Approach》-MSR

**Comment by PureNatural** [comment]
11月份
《Sentiment Analysis in Code Annotation Comments on Github》-MSR 4 page Technical Paper

**Comment by birdflyi** [comment]
《OpenRefNet：A dataset on reference networks of open source databases》-ICPC ERA

**Comment by bifenglin** [comment]
目前以上会议都已经完成并且提交，我们是不是需要再下一步论文投稿促进工作，按季度再开一个论文促进贴?@xiaoya-yaya @will-ww

**Comment by xiaoya-yaya** [comment]
@tyn1998 的 ICPC DEMO 和 @zhicheng-ning 的 MSR Data and Tool 都还在投稿中。

**Comment by tyn1998** [comment]
<img width="1367" alt="image" src="https://github.com/X-lab2017/open-research/assets/32434520/9f36871b-80cd-4ce8-88ef-68676a4b790f">

Submitted!

**Comment by will-ww** [comment]
最近一波论文投稿汇总如下：

- **OpenGalaxy: An interactive exploration platform for a visualized GitHub Full Domain collaboration network** (ICPC Demo, @longyanz)
- **Hypercrx: A browser extension for insights into GitHub projects and developers** (ICPC Demo, @tyn1998 )
- **StellarTop: An Integrated Multi-Topic Dataset on GitHub Repositories** (MSR Demo, @Zzzzzhuzhiwei )
- **Evaluating Open Source Project Influence based on NPM Ecology Dataset**  (MSR Demo, @frank-zsy @xiaoya-yaya @huangfan0)
- **GHDU: A Comprehensive Dataset of GitHub Developer Information** (MSR Demo, @zhicheng-ning )
- **Global Insights for GitHub Developers: A Fine-Grained Geographic Dataset and Analysis**  (MSR Demo,@JiahengPeng)

**Comment by bifenglin** [comment]
- Uncover the Risks of Outdated Third-Party Components in Software Supply Chains: Insights from the NPM Ecosystem(ICPC Technical Paper, @bifenglin )

- Assessing Maintainability Risks in the Open Source Software Supply Chain: A Novel Quality Model Approach(MSR Technical Paper, @bifenglin)

**Comment by will-ww** [comment]
**Updated**: [[ICSE SEIP 2024](https://conf.researchr.org/track/icse-2024/icse-2024-software-engineering-in-practice)] Accepted notification for submission "**Motivating Open Source Collaborations Through Social 
Network Evaluation: A Gamification Practice from Alibaba**"

**Comment by tyn1998** [comment]
> **Updated**: [[ICSE SEIP 2024](https://conf.researchr.org/track/icse-2024/icse-2024-software-engineering-in-practice)] Accepted notification for submission "**Motivating Open Source Collaborations Through Social Network Evaluation: A Gamification Practice from Alibaba**"

太强了，我也想有Updated 🤩

**Comment by tyn1998** [comment]
> > **Updated**: [[ICSE SEIP 2024](https://conf.researchr.org/track/icse-2024/icse-2024-software-engineering-in-practice)] Accepted notification for submission "**Motivating Open Source Collaborations Through Social Network Evaluation: A Gamification Practice from Alibaba**"
> 
> 太强了，我也想有Updated 🤩

Updated：

![image](https://github.com/X-lab2017/open-research/assets/32434520/6f9439e0-58a1-4444-9e5b-35b4a0826c40)

🎉

**Comment by longyanz** [comment]
![1704846905021](https://github.com/X-lab2017/open-research/assets/91717658/bb9b8dcd-404b-41c9-8f75-1f0a9edb9d8f)
好耶！

**Comment by will-ww** [comment]
> > > ## OSSLab：Open Source Software Data Analytics Lab
> > > ### 官网
> > > https://osslab-pku.org/
> > 
> > 
> > 前面也整理了下周老师实验室的论文集，供大家参考与系统阅读：https://xlab2017.yuque.com/msdpvs/fzem1h/32741796
> 
> 最近正在研究相关论文，这个语雀似乎要权限，可以开放学习一下么？

帮忙加一下？@tyn1998

**Comment by PureNatural** [comment]
OpenRank: 一种面向异质信息网络的高维中心性评估算法
帮frank学长完成的一篇关于openrank算法的论文，计划月底投出

OpenPerf去年8月底投出，现在进入3审阶段，预计8月初返回结果

OpenDigger英文版需要大修后再投出，预计要到暑期投出
