### ISSUE TITLE
[CFP] DASFAA 2024 - CCF B

### ISSUE THREAD

**Issue by will-ww** [X-lab2017/open-research#242]
### Description

DASFAA 作为 CCF B 类的会议，是一个非常不错的数据库领域的学术交流平台。学院很多老师也都长期参与其中，大家可以多尝试~

Due Dates - All deadlines are 23:59 Anywhere on Earth (AoE) time.

**Due Dates for Reseach Papers** ([CFP](https://www.dasfaa2024.org/call-for-research-papers/))
- Abstract submission due：December 15, 2023
- Paper submission due：December 22, 2023
- Acceptance notification：March 15, 2024

**Due Dates for Industry Papers** ([CFP](https://www.dasfaa2024.org/call-for-industry-papers/))
- Paper submission due：January 25, 2024
- Acceptance notification：March 12, 2024

**Due Dates for Demo Papers** ([CFP](https://www.dasfaa2024.org/call-for-demo-papers/))
- Paper submission due：February 10, 2024
- Acceptance notification：March 19, 2024

<div align=center>
<img src="https://github.com/X-lab2017/open-research/assets/15010826/d17e48a6-275d-43e4-b774-046d9aaba85d" width="350px">
</div>

想去日本体验与交流的同学抓紧了~

**Comment by bifenglin** [comment]
https://www.dasfaa2024.org/call-for-demo-papers/
一直想把OSS-Chat项目搞好，发到demo track上面，截止日期是2月，时间应该正好，先占个坑。
