### ISSUE TITLE
[ICSED] 近期适合投递的会议

### ISSUE THREAD

**Issue by bifenglin** [X-lab2017/open-research#248]
### Description

http://www.icsed.org/cfp.html
这个会议主题比较契合，EI检索。

<img width="1326" alt="image" src="https://github.com/X-lab2017/open-research/assets/15813364/4cbdd699-968d-4f8b-8fe8-b14712379efe">

截止日期1月10日，研二研三有时间的同学可以试一试，在香港。

<img width="507" alt="image" src="https://github.com/X-lab2017/open-research/assets/15813364/61e23d8d-e812-4568-b2ee-feb12e766381">

**Comment by will-ww** [comment]
非 CCF 列表会议，不作为优先考虑哈~ :-)
