### ISSUE TITLE
关于学院开展研究生学术沙龙的讲座安排

### ISSUE THREAD

**Issue by PureNatural** [X-lab2017/open-research#258]
### Description

时间：今年3月份
讲座：参考往年的流程，需要有3-4个讲座，一般第一个讲座需要一位老师先讲，后面两个由学生讲。
还需要一位学生负责拍照，可能要麻烦专业摄影师 @zhicheng-ning 同学到时候帮一下忙

我觉得可以参考年会的汇报安排
1. OpenRank @will-ww 
2. OpenDigger @PureNatural 
3. OpenPerf @bifenglin 

王老师先开个头，然后我和老毕再接着讲，看看大家有什么其他意见。

**Comment by will-ww** [comment]
目前邀请了几个外面的专家一起，准备在 3 月 18 日开展，包括复旦的陈阳老师、天空开物的庄表伟老师。

主题（初定）：**如何做开源领域的学术研究工作？**

时间：3 月 18 日（周一），下午 3 点 ~ 6 点

- 报告 01：开源世界的学术问题（庄表伟）
- 报告 02：OpenResearch —— 用开源的方法做开源的研究（王伟）
- 报告 03：待定（开源与 EasyGraph 方向）（陈阳，复旦大学）
- 报告 04：如何做开源领域的学术研究 —— 以 ICSE 论文工作为例（夏小雅，博士生）
- 报告 05：OpenPerf —— 面向开源生态可持续发展的数据科学基准测试体系（韩凡宇，博士生）

持续更新中~

**Comment by will-ww** [comment]
本次研究生学术沙龙的开展，大致可以达到如下几个方面的效果：

1. 作为新学期学院第一次学术沙龙活动，贡献内容的同时，也借此机会将 X-lab 开放实验室的学术研究方法与部分成果做点系统的梳理
2. 和研究生的开源课程联动，邀请外部专家过来交流的同时，也向大家宣传数据学院在开源方向的研究成果与思路，以便更好的开展外部合作（本次邀请的[天工开物开源基金会](https://github.com/X-lab2017/open-wonderland/issues/369)和[复旦大学团队](https://github.com/orgs/X-lab2017/discussions/355)，都是后续重要的合作伙伴）
3. 借此机会推动实验室[年度重要工作](https://github.com/X-lab2017/open-wonderland/issues/364)（OpenRank、OpenPerf 等），并继续邀请开源领域的潜在合作伙伴一同参加（例如蚂蚁、开放原子、南大等）

**Comment by will-ww** [comment]
内容全部确定，宣传海报已发出：https://mp.weixin.qq.com/s/2k8I-ixjvyq-ys-IZNrbmg

<div align=center>
<img src="https://github.com/X-lab2017/open-research/assets/15010826/c9620d88-f84c-4f36-a6d3-23ef5eef8642" width="500px">
</div>

**Comment by PureNatural** [comment]
学术沙龙总结：https://mp.weixin.qq.com/s/v0Vzn2XEZBHRV4uNrOuVnw
