### ISSUE TITLE
如何构建一个论文的筛选和落库流程？

### ISSUE THREAD

**Issue by will-ww** [X-lab2017/open-research#3]
我觉得这个项目中，我们可以构建一个开源领域的研究论文收集流程：

1. 贡献者根据模板填写推荐的论文信息和论文全文，并列举推荐该论文的原因；
2. 审核团队，根据推荐信息，然后判断是否符合我们阅读论文的需求，通过或不通过
3. 通过的论文信息，落到仓库中，供大家阅读和参考
4. 同时，还可以补充该论文的相关资源，例如原作者的演讲或我们的分享视频或PPT

这里需要制定几个内容包括：
- 考虑上述这些因素的论文推荐模板
- 论文评审的标准和要求
- 论文推荐、分享、后续补充资料等步骤的完整流程
- 论文分类或标签体系，方便快速定位感兴趣的论文
- 分享完后，可以跟一个技术博客进行总结，既提升自己也丰富信息

大家可以补充，目的还是系统而高效的阅读分享关键性论文，深度优先、兼顾知识面的扩展~ @birdflyi

**Comment by birdflyi** [comment]
尝试：1. [TPIC](https://shimo.im/docs/5rk9d7negKS8NMqx#anchor-NrKN): [**Topics**](https://www.mubucm.com/doc/58RDuDR3QJG#m) -> Problems -> Ideas -> ConcreteWorks
- 目前在Topics层已通过[调查](https://shimo.im/docs/473QylQmJpsMEE3w#anchor-9Hft)/[文献调查](https://pan.baidu.com/s/1tBj2Vz7GdEw5Ma1mNVDLzw?pwd=1234)给出了一个广而不精的[**Topics**](https://www.mubucm.com/doc/58RDuDR3QJG#m)地图。
- [X-lab2017/OpenResearch#2](https://github.com/X-lab2017/OpenResearch/pull/2)依据Topics地图中的话题给出了若干示例，并在标题中使用**加粗**来凸出话题。希望在[README.md](https://github.com/X-lab2017/OpenResearch/blob/main/README.md)中增加**Tag**标签列来表征文献所属的话题分类（可以考虑根据分类树建立标签的编码表，压缩占用的空间），增加**No.**文献编号列方便管理。
- 计划将TPIC4种视角的文献分别用4个表格列出。
- Paper列中的文献标题可以加[Link]指向源文献或[LocaLlink]指向不易获取的存储在PDF目录下的文献。
- 增加详细理由文档，需要提供指向的文献编号，分类标签，详细理由。等待收集到一定数量，构建分类树和标签体系。
- 文献相关的资源链接包括但不限于：[Link]即PaperURL、[PPT]、[Notes]、[Video]、[(Project)]如[[TensorFlow](https://github.com/tensorflow/tensorflow)]、[Website]如[[Website](http://www.x-lab.info/project/)]、[Blog]、[LocalLink]上传到本地的资源。

流程：start.开始推送 -> a.推送文献有标签？ -[Y]-> b.标签在已有体系内（推荐理由类别有效）？ -[Y]-> c.详细理由review通过？ -[Y]-> d.有资源链接？ -[Y]-> e.合并-[Y]-> end.结束
a. -[N]-> start.添加标签重提PR
b. -[N]-> i.提PullRequest修改标签体系 --> 审核PR通过？-[Y|N]-> c.|start.修改标签重提PR
c. -[N]-> start.修改理由重提PR
d. -[N]-> j.提上传相关资源的TODO issue？ -[Y|N]-> e.|[k.PRComment暂无资源 -[Y|N]-> e.|start.]
追加资源信息可单独增加一个Issue类型的Tag。

标准：
1) 示例

| No. | Paper | Author | Conf&Journal | Year | Rank | Tags |
|---|---|---|---|---|---|---|
|T1|What Makes a Great Maintainer of Open Source Projects?|Edson Dias et al.|ICSE|2021|A|`开发者`|

No.为单调递增序列，T1代表Topic系列编号为1的Paper，共有TPIC4个系列。
No.和Tags列若有其他类别，可用`,`隔开，如`T1,P1`，Tags需要用\`和\`括起来。
2) 标准
Tag优先，以下综合考虑：Year推荐最近5年内，arXiv文献可以通过当前引量和Author信息初步判定，Conf&Journal推荐CCF B类及以上，部分高引用的C类推荐应说明原因。

**Comment by bifenglin** [comment]
楼上确实写的很全很详细，我认为topic不宜过多，过多就导致选择障碍和理解障碍，还是从我们目前关注的一些问题着手，不需要广度很广适合实验室研究方向就好。然后在readme中写好
这边我初步列了一下我认为的相关topic：
- openperf
- NLP（包括知识图谱）
- anomaly detection（包括github机器人识别）
- data classification
- data cluster
- association analysis
不需要专注于某一业务领域，因为方法可以触类旁通，在其他领域下面的方法有可能启发本领域的创新。topic下面确实可以有很多challenge，这些challenge是我们总结的问题，个人认为不需要在论文筛选这边分开，而是在各个专门的研究challenge下面进行引用总结，这样会更清晰，也能减轻论文提交和review人员的工作量和减少共识问题。标准示例完全可以引用楼上的格式。

**Comment by birdflyi** [comment]
那么可以先开一个用于收集Topic的常开Issue，如果大家关心的业务问题不多，就不分Topic的体系。如果业务问题多而且杂，建议还是分一下，方便以后添加新的话题。
我觉得Topic的维护人员不一定是我们，可以拉有需求的人来OpenResearch中的话题侧提需求Issue，我们可以设置标记表示我们正在关心的话题。

**Comment by bifenglin** [comment]
嗯嗯，可以开个适于实验室的topic体系的issue，先按一个topic体系试起来，然后通过issue慢慢调整完善，这是个长期issue。

**Comment by birdflyi** [comment]
目标更改：
[TPIC](https://shimo.im/docs/5rk9d7negKS8NMqx#anchor-NrKN): [Topics](https://www.mubucm.com/doc/58RDuDR3QJG#m) -> Problems -> Ideas -> ConcreteWorks 中暂时仅维护Topic与Problems两个分类体系。
1.  便于标注。
2.  我认为应对当前面临的论文标注是足够的。
