### ISSUE TITLE
[Proposal] 关于文件存储服务的选择

### ISSUE THREAD

**Issue by will-ww** [X-lab2017/open-research#35]
今天和大家讨论了下实验室论文、数据、视频、PPT等文件存储的问题，形成几个共识：

@will-ww
- 这个是我们目前的OSS服务的访问地址是这个吧 [OSS](http://oss.x-lab.info)，我们的pdf论文等资料，放在哪里比较合适？
- OSS
- 语雀
- NextCloud

@frank-zsy 
- 是这个地址。OSS 其实比较合适放静态文件，分发速度也快，完全公开访问的，但问题就是编辑比较麻烦，需要在阿里云的控制台，不是任何人都可以随意放东西上去的。语雀的话我不是很确定，可能也可以，而且说不定支持各种富媒体的在线预览。NextCloud 不太建议，毕竟要自己搭服务，运维成本高，稳定性差，带宽也有限，不过本地支持确实比较方便，可以快速同步。
- 其实自己用的话都还好，有个地方同步东西就行，各种网盘也都没问题，但团队用就是个问题，两年前用 NextCloud 我觉得倒也还好，虽然偶尔会挂掉，但问题就是最后变得非常乱，各种文件都扔上去，就很难维护了。

@tyn1998 
- 我觉得语雀的资源知识库挺好的。大家传方便，下载的人也方便，速度也快
- 语雀支持的格式有限，但是zip压缩包都可以的
- 图片文档视频全都可以，我在上传的时候看到灰的不能传的也只是.dmg这种mac下的程序安装包格式

**Comment by bifenglin** [comment]
主要问题是可公开性和团队协作性：

**Comment by bifenglin** [comment]
主要问题是可公开性和团队协作性：
OSS：

**Comment by will-ww** [comment]
因此，我们基本上就选择“语雀”作为实验室内外部的结构化知识库了，通过权限进行设置外部访问。OSS 作为快速分发静态文件（例如开放数据），百度云盘就是作为一个更加自由的后备选项了。

目前在“语雀”下有个 x-kb-sharing 的团队分享知识库，下面设置若个目录，进行选择性的文件贡献：
- x-paper-pub：公开论文
- x-report-pub：成员技术报告、白皮书、PPT等公开内容
- x-pub：其他公开分享的内容

- x-thesis：内部成员学位论文
- x-book：内部书籍分享（版权材料，仅内部）
- x-vedio：内部实验室视频资源
- x-close：内部其他数据分享

具体参见：https://xlab2017.yuque.com/msdpvs

大家试验下，公开性和可写作性是否可以支持~

**Comment by tyn1998** [comment]
这是我的视角：
<img width="912" alt="image" src="https://user-images.githubusercontent.com/32434520/166412983-542a61f0-418d-4ee7-b041-adcd9cd03b83.png">
几个内部仓库我目前看不到~

**Comment by bifenglin** [comment]
主要问题是可从公开性，团队协作性和维护成本三个方面考虑：
- OSS：
  1. 可公开性就类似于文件服务器，可以直接访问链接下载，但是没有在线浏览等功能。
  2. 团队协作性较差，需要制定合适的目录标准规范，防止内容过冗杂。
  3. 由阿里云维护，不需要考虑维护成本，存储成本每TB每天1毛钱，较低。
 - 语雀：
  1. 可公开性（不确定外部联系人的意思是不是任何匿名用户都可自由访问）需要验证。可在线浏览各种大部分格式文件。
  2. 团队协作较好，有版本回溯，有不少目录层级和权限控制。
  3. 维护成本低，免费网盘容量10G，扩充网盘可能需要购买（这个教育版不清楚能否免费扩网盘容量）。正常商业版500G网盘一年七八千块钱。
 - 自建云盘
   1. 可公开性较好，可以直接访问链接下载，有在线浏览大部分格式功能。
   2. 团队协作需要制定公共目录的标准规范。
   3. 需要自己维护，维护成本较高
  

综上所述，若是语雀匿名用户可以访问，使用语雀性价比较高，

**Comment by tyn1998** [comment]
刚刚和王老师做了很多实验，有以下发现：
- 任何人想使用语雀，必须注册登录
- 空间外部人员是无法访问空间内的任何公开内容的
- 成为空间成员或**外部联系人**就可以访问

**Comment by bifenglin** [comment]
语雀这个开放性还是有些问题，匿名用户不能访问。

**Comment by tyn1998** [comment]
毕博说的匿名用户是指未注册用户吗？这一点语雀和石墨很不一样，它一定要注册了才能用

**Comment by bifenglin** [comment]
是的 未注册用户访问，这样开放性就差了点，不过有个优点，能知道那些人访问。。。。

**Comment by will-ww** [comment]
> 是的 未注册用户访问，这样开放性就差了点，不过有个优点，能知道那些人访问。。。。

是的，其实我们不用满足匿名用户的访问问题，像访问就麻烦点，按照我们的规则来即可。

所以，我也比较推荐用语雀，首先还是满足我们自己的需求。其他人要下载的话：
1. 成为语雀的注册用户
2. 点击我们分享的链接，加入X-lab的空间

这样，我们也能够有额外的留痕数据，应该也是有好处的。

**Comment by will-ww** [comment]
> 是的 未注册用户访问，这样开放性就差了点，不过有个优点，能知道那些人访问。。。。

是的，其实我们不用满足匿名用户的访问问题，像访问就麻烦点，按照我们的规则来即可。

所以，我也比较推荐用语雀，首先还是满足我们自己的需求。其他人要下载的话：
1. 成为语雀的注册用户
2. 点击我们分享的链接，加入X-lab的空间

这样，我们也能够有额外的留痕数据，应该也是有好处的。

**Comment by bifenglin** [comment]
是的 这个这个作为我们的文档库。若是我们要公开哪些内容，可以考虑从x-lab门户官网入手，这个一般更新频率略低的。

**Comment by will-ww** [comment]
初步建立了一下 X-KB 知识库，大家可以 Reveiw 下，看看体验如何：https://xlab2017.yuque.com/docs/share/6554c3b8-9546-4b86-ad18-b220d07d8017?# 《🤝 X-KB 知识库说明文档》

@bifenglin @tyn1998 @frank-zsy

**Comment by bifenglin** [comment]
大家贡献的贡献在语雀的哪里呢？是不是需要专门创建`X-KB`的团队然后创建这些主题的知识库？还是直接在`内部团队`里创建这些主题的知识库？还是直接在`内部团队里`创建一个`X-KB`的知识库然后创建这些主题目录。

我建议直接在内部团队里创建这些知识库，然后将一些知识内容合并一下。

**Comment by tyn1998** [comment]
X-KB团队昨天就已经创建啦：
<img width="1345" alt="image" src="https://user-images.githubusercontent.com/32434520/166615765-1891ccda-902c-4e6b-af3c-d519041a05bd.png">
这是现在我的视角~

> 然后将一些知识内容合并一下

的确与之前一些知识库有重复，需要整理一下，只要留一个就行了

**Comment by tyn1998** [comment]
个人感觉，语雀中的任何知识库本来就叫“知识库了”，X-KB（X knowledge base）团队又创建了许多知识库，这样的命名有点令人误解。这个团队跟open-research高度相关的话，叫X-research、X-academic、X-resource个人感觉更直观

**Comment by will-ww** [comment]
是的，大家多从全局的角度看看。我这边之所以没有在已有的知识库上建立，就是做一些探索，目前看”语雀“的知识库之间的迁移与整合，应该还是能够很好支持的。前面的各类知识库，基本都是大家（包括我）比较随性的扔上去的，没有什么规则和流程。目前已有的知识库，都是干什么的有文档不？@bifenglin 

也正好借这个机会系统梳理下，原则就是：
- 除非必要，无需多建
- 建设的知识库，一定要用起来，而不是网盘，和我们的日常事务关联起来
- 和GitHub、自动化联动的，尽量自动化起来
- 需要有专门的同学（轮流也行）日常维护

大家一起思考下哈~

**Comment by will-ww** [comment]
语雀在他的官方文档中，举了几个案例，大家可以参考下：
● [语雀](https://yuque.com/yuque)
● [Ruby China](https://yuque.com/ruby-china)
● [Eggjs](https://yuque.com/egg)

我们争取也做成一个案例哈~ :-)

**Comment by will-ww** [comment]
![image](https://user-images.githubusercontent.com/15010826/166619073-165fe6c4-f283-4172-a834-991b93cc0a3e.png)

这种结构化的体验，还是很不错的~

**Comment by tyn1998** [comment]
<img width="312" alt="image" src="https://user-images.githubusercontent.com/32434520/166619304-2f8ac998-dee0-4341-bc38-50306f12ee40.png">
哈哈，忠实用户在此，Mac客户端常驻桌面

**Comment by will-ww** [comment]
另外，语雀的开放API：https://www.yuque.com/yuque/developer/api

是不是也还可以做点事情： @frank-zsy

**Comment by will-ww** [comment]
这里有个有意思讨论：https://www.yuque.com/yuque/developer/ogibph

![image](https://user-images.githubusercontent.com/15010826/166624376-631fc7a7-842c-407b-b7d0-41fa2e0c9999.png)

**Comment by frank-zsy** [comment]
> 另外，语雀的开放API：https://www.yuque.com/yuque/developer/api
> 
> 是不是也还可以做点事情： @frank-zsy

是的，之前就调研过，文档类平台基本都有开放 API，但有两个问题无法绕开：
- 文档协议不同，不同的平台没有统一的规范，功能也不尽相同，开放程度也不同，很难抽象成同一套接口
- 平台的身份权限体系不兼容，语雀使用的是三层权限体系，GitHub 是两层权限体系，石墨是更自由的团队权限体系，目前在权限上不太能统一管理

综上，现在做集成的话，文档平台统一集成难度较大，而且由于权限体系不开放，基本只能做一些内容同步性的工作。

**Comment by bifenglin** [comment]
https://xlab2017.yuque.com/staff-kbz9wp/freshman/kx9wny
这个是各个知识库介绍。

**Comment by will-ww** [comment]
> > 另外，语雀的开放API：https://www.yuque.com/yuque/developer/api
> > 是不是也还可以做点事情： @frank-zsy
> 
> 是的，之前就调研过，文档类平台基本都有开放 API，但有两个问题无法绕开：
> 
> * 文档协议不同，不同的平台没有统一的规范，功能也不尽相同，开放程度也不同，很难抽象成同一套接口
> * 平台的身份权限体系不兼容，语雀使用的是三层权限体系，GitHub 是两层权限体系，石墨是更自由的团队权限体系，目前在权限上不太能统一管理
> 
> 综上，现在做集成的话，文档平台统一集成难度较大，而且由于权限体系不开放，基本只能做一些内容同步性的工作。

没问题的，只是探索下可能性。即便内容同步的话，也算有不少用途了~

**Comment by will-ww** [comment]
> https://xlab2017.yuque.com/staff-kbz9wp/freshman/kx9wny 这个是各个知识库介绍。

我同时也在尝试用我们提出的开源治理与运营框架来套 X-lab，还是比较可行的，可以联动着一起看看~
