### ISSUE TITLE
关于论文推荐流程的讨论

### ISSUE THREAD

**Issue by frank-zsy** [X-lab2017/open-research#36]
- https://github.com/X-lab2017/open-research/blob/888f98b988f770e61f2ca680851326bee5261764/RecPaper.md?plain=1#L16 建议分类必选，并且按照 Opendium 的分类，可能存在多个维度，最好都需要选择，若没有对应分类可以选择“其他”。原因是对于推荐者而言，论文内容大致是已知的，进行这几个维度的分类的心智成本不高，但长期收益很大，可以形成较好的标签数据，论文也有更好的依据可以进行分类存放，如果这个工作后续再集中人工来做，成本是更高的。
- https://github.com/X-lab2017/open-research/blob/888f98b988f770e61f2ca680851326bee5261764/RecPaper.md?plain=1#L28 目前 Hypertrons 是没有能力做 Markdown 文档的合入的，尤其是人工和机器同时协作的文件，因为这需要对 Markdown 文档本身的格式内容进行结构化的解析，而且如果中间出现文档结构上的变动就会失效。因为 Hypertrons 之前在其他仓库的提交自动化文件几乎均为全量覆盖的模式，这里还是建议审核通过后由推荐人提交 PR。

**Comment by xiaoya-Esther** [comment]
分类必选我和Frank的观点一致。
另外：

> 审核团队：X-lab.PhD

X-lab.PhD 是不是会建一个 GitHub team？我目前还没找到～

**Comment by frank-zsy** [comment]
> 分类必选我和Frank的观点一致。 另外：
> 
> > 审核团队：X-lab.PhD
> 
> X-lab.PhD 是不是会建一个 GitHub team？我目前还没找到～

应该可以用 GitHub Team 来管理，毕竟维护频率也非常低，需要每年进行一次人员调整

**Comment by will-ww** [comment]
> > > 审核团队：X-lab.PhD
> > 
> > 
> > X-lab.PhD 是不是会建一个 GitHub team？我目前还没找到～
> 
> 应该可以用 GitHub Team 来管理，毕竟维护频率也非常低，需要每年进行一次人员调整

是的，整个可以直接映射到我们的“1.2.4 社区架构”整个部分：https://xlab2017.yuque.com/msdpvs/me6vqg/nprrfi#aeWoC

**Comment by will-ww** [comment]
> 

好，我更新一下，先人工做起来~
