### ISSUE TITLE
建立 2 个 Issue Tmplage

### ISSUE THREAD

**Issue by will-ww** [X-lab2017/open-research#43]
我觉得入库的表结构没有问题～

推荐时，我建议可以像 open digger 提标签数据一样，直接用 Issue Template 给出论文推荐模板，Discussion 目前似乎还不支持模板功能，不过在 Discussion 下面的格式可以更加自由一些。

_Originally posted by @xiaoya-Esther in https://github.com/X-lab2017/open-research/issues/38#issuecomment-1126601338_

**Comment by will-ww** [comment]
请 @xiaoya-Esther 帮忙建立讲个 Temalage（全英为的，尽量考虑到国际化）：

**Paper recomandation, PaperRec 模板（7要素）**：
- 题目：开源软件社区开发者协作网络——以 CloudFoundry 社区为例
- 会议或期刊名称：复杂系统与复杂性科学
- 年份：2019
- 级别：无
- 分类或关键词：复杂网络、开源社区演化
- 推荐理由：从复杂网络的视角研究开源社区协作关系的演化，对实验室制作图数据集，以及用复杂网络中的方法进行研究，都有很好的启发
- 全文链接如下

**Reading plan proposal, ReadingPro 模板（9要素）**：
- 论文题目（Title）：论文完整正式的标题
- 作者与机构背景（Author and affiliation）：主要作者与作者所属机构或实验室的背景信息
- 发表年份（Year）：正式发表或公开上传的年份
- 会议或期刊名称（Conference or Journal）：论文发表的会议或期刊名称
- 级别（参照 CCF 级别）（Ranking）：如会议和期刊列入 CCF 的分级中，可以标注上
- 分类标签：参照开源纲目[[Opendium](https://github.com/X-lab2017/open-research/tree/main/Opendium)]中的分类体系，打上 1 ~ 5 个标签
- 论文链接（Link）：论文全文的网络链接信息，同时放入[[语雀知识库](https://xlab2017.yuque.com/msdpvs/dtg7ew)]中
- 选题原因（Select reason）：简单描述下选题的原因，特别是和实验室研究方向的关联
- 其他补充（可选）（Supplementary）：其他可选的背景补充信息

**Comment by will-ww** [comment]
已建了一个论文推荐模板了，感觉不错。@xiaoya-Esther 

![image](https://user-images.githubusercontent.com/15010826/168453645-eee71667-0525-4674-87d3-cb7805c436ac.png)

阅读分享的模板也可以继续了，可以同时参考下翁振杰的这个 issue：https://github.com/X-lab2017/open-research/issues/44

**Comment by xiaoya-Esther** [comment]
👌👌👌

**Comment by will-ww** [comment]
Great, many thanks~

![image](https://user-images.githubusercontent.com/15010826/168475132-77535f9a-844d-46e4-a0e9-2270fefb5d93.png)
