### ISSUE TITLE
[PaperRec] What Makes a Great Maintainer of Open Source Projects?

### ISSUE THREAD

**Issue by zhicheng-ning** [X-lab2017/open-research#62]
## I wish to recommend a paper

- Title: What Makes a Great Maintainer of Open Source Projects?
- Year: 2021
- Conference or Journal: ICSE
- Rank: A
- Keywords: 开源软件、开源维护者、独特属性
- Reason for Recommendation: 通过访谈的方式获取优秀维护者的属性、创建概念性框架、属性评级问卷调查
- Link: https://xlab2017.yuque.com/msdpvs/dtg7ew/26074782

@X-lab2017/x-lab-phd

**Comment by zhicheng-ning** [comment]
Summary link ：https://www.yuque.com/shibudengqinsheng/ggwvkm/gx84ci

**Comment by will-ww** [comment]
邀请 @birdflyi 帮忙入库与更新链接~

**Comment by birdflyi** [comment]
> Summary link ：https://www.yuque.com/shibudengqinsheng/ggwvkm/gx84ci

在把 [[[Copy](https://github.com/X-lab2017/open-research/issues/PDF/What%20Makes%20a%20Great%20Maintainer%20of%20Open%20Source%20Projects.pdf)](./PDF/What%20Makes%20a%20Great%20Maintainer%20of%20Open%20Source%20Projects.pdf)] 这个仓库内的PDF备份替换成指向语雀仓库的链接后，需要删除仓库内的PDF吗？

**Comment by zhicheng-ning** [comment]
> 需要删除仓库内的PDF吗

我不清楚其他地方引用的 pdf 链接是仓库内的文件链接还是语雀仓库的链接

**Comment by birdflyi** [comment]
> > 需要删除仓库内的PDF吗
> 
> 我不清楚其他地方引用的 pdf 链接是仓库内的文件链接还是语雀仓库的链接

都有的，之前讨论，目前在逐渐迁移到语雀，迁移的默认位置在这里讨论过：[默认的资源位置-v1](https://github.com/X-lab2017/open-research/issues/38#issuecomment-1126969593)

**Comment by zhicheng-ning** [comment]
> 都有的，之前讨论，目前在逐渐迁移到语雀，迁移的默认位置在这里讨论过：[默认的资源位置-v1](https://github.com/X-lab2017/open-research/issues/38#issuecomment-1126969593)

ok，那《 What Makes a Great Maintainer of Open Source Projects?》这篇论文的 pdf 可以删掉的~

**Comment by birdflyi** [comment]
除了这个Copy Link指向目录的调整，还有就是本Issue Link的重复记录问题？（前置讨论结果：https://github.com/X-lab2017/open-research/issues/38#issuecomment-1126622367 中的 [论文列表库](https://github.com/X-lab2017/open-research/blob/main/openlist.md) 和 [这学期的安排](https://github.com/X-lab2017/open-research/tree/main/agenda)）

目前有两个地方需要关联本Issue #62：
1. https://github.com/X-lab2017/open-research/tree/main/agenda 的 `关联 Issue` 列
2. https://github.com/X-lab2017/open-research/blob/main/openlist.md 的 `History` 列

这两处是重复的吗？是不是可以删除一个？
@will-ww @frank-zsy @xiaoya-Esther @bifenglin

**Comment by will-ww** [comment]
> 除了这个Copy Link指向目录的调整，还有就是本Issue Link的重复记录问题？（前置讨论结果：[#38 (comment)](https://github.com/X-lab2017/open-research/issues/38#issuecomment-1126622367) 中的 [论文列表库](https://github.com/X-lab2017/open-research/blob/main/openlist.md) 和 [这学期的安排](https://github.com/X-lab2017/open-research/tree/main/agenda)）
> 
> 目前有两个地方需要关联本Issue #62：
> 
> 1. https://github.com/X-lab2017/open-research/tree/main/agenda 的 `关联 Issue` 列
> 2. https://github.com/X-lab2017/open-research/blob/main/openlist.md 的 `History` 列
> 
> 这两处是重复的吗？是不是可以删除一个？ @will-ww @frank-zsy @xiaoya-Esther @bifenglin

是的！

1 是本学期的论文阅读安排
2 是 X-lab 的所有论文库

因此，建议论文推荐的issue，保留在 openlist 的关联上，大家可以知道这篇文章是怎么来的，而分享的所有信息可以包含到 agenda 的上面，用来追踪信息，如果也包括推荐的历史信息，其实也不是不可以~

#62 是 [PaperRec] 标签~

**Comment by birdflyi** [comment]
> > 除了这个Copy Link指向目录的调整，还有就是本Issue Link的重复记录问题？（前置讨论结果：[#38 (comment)](https://github.com/X-lab2017/open-research/issues/38#issuecomment-1126622367) 中的 [论文列表库](https://github.com/X-lab2017/open-research/blob/main/openlist.md) 和 [这学期的安排](https://github.com/X-lab2017/open-research/tree/main/agenda)）
> > 目前有两个地方需要关联本Issue #62：
> > 
> > 1. https://github.com/X-lab2017/open-research/tree/main/agenda 的 `关联 Issue` 列
> > 2. https://github.com/X-lab2017/open-research/blob/main/openlist.md 的 `History` 列
> > 
> > 这两处是重复的吗？是不是可以删除一个？ @will-ww @frank-zsy @xiaoya-Esther @bifenglin
> 
> 是的！
> 
> 1 是本学期的论文阅读安排 2 是 X-lab 的所有论文库
> 
> 因此，建议论文推荐的issue，保留在 openlist 的关联上，大家可以知道这篇文章是怎么来的，而分享的所有信息可以包含到 agenda 的上面，用来追踪信息，如果也包括推荐的历史信息，其实也不是不可以~
> 
> #62 是 [PaperRec] 标签~

OK。我的理解是：
1. **推荐Issue**需要放入[openlist](https://github.com/X-lab2017/open-research/blob/main/openlist.md)的`History`列，根据推荐Issue #62 的标题的[PaperRec]开头，需要以 [[PaperRec](https://github.com/X-lab2017/open-research/issues/62)] 标签的形式放在`关联 Issue`列；
2. [agenda](https://github.com/X-lab2017/open-research/tree/main/agenda)的`关联 Issue`列尽可能把分享的讨论流程全覆盖，可以重复放入**推荐Issue**，并且附带其他相关的讨论或资源链接。

其他问题：[agenda](https://github.com/X-lab2017/open-research/tree/main/agenda)的`关联 Issue`列是否需要像[openlist](https://github.com/X-lab2017/open-research/blob/main/openlist.md)的`History`列一样，统一一下Issue的标签表示形式？

**Comment by will-ww** [comment]
> > > 除了这个Copy Link指向目录的调整，还有就是本Issue Link的重复记录问题？（前置讨论结果：[#38 (comment)](https://github.com/X-lab2017/open-research/issues/38#issuecomment-1126622367) 中的 [论文列表库](https://github.com/X-lab2017/open-research/blob/main/openlist.md) 和 [这学期的安排](https://github.com/X-lab2017/open-research/tree/main/agenda)）
> > > 目前有两个地方需要关联本Issue #62：
> > > 
> > > 1. https://github.com/X-lab2017/open-research/tree/main/agenda 的 `关联 Issue` 列
> > > 2. https://github.com/X-lab2017/open-research/blob/main/openlist.md 的 `History` 列
> > > 
> > > 这两处是重复的吗？是不是可以删除一个？ @will-ww @frank-zsy @xiaoya-Esther @bifenglin
> > 
> > 
> > 是的！
> > 1 是本学期的论文阅读安排 2 是 X-lab 的所有论文库
> > 因此，建议论文推荐的issue，保留在 openlist 的关联上，大家可以知道这篇文章是怎么来的，而分享的所有信息可以包含到 agenda 的上面，用来追踪信息，如果也包括推荐的历史信息，其实也不是不可以~
> > #62 是 [PaperRec] 标签~
> 
> OK。我的理解是：
> 
> 1. **推荐Issue**需要放入[openlist](https://github.com/X-lab2017/open-research/blob/main/openlist.md)的`History`列，根据推荐Issue [[PaperRec] What Makes a Great Maintainer of Open Source Projects? #62](https://github.com/X-lab2017/open-research/issues/62) 的标题的[PaperRec]开头，需要以 [[PaperRec](https://github.com/X-lab2017/open-research/issues/62)] 标签的形式放在`History`列；
> 2. [agenda](https://github.com/X-lab2017/open-research/tree/main/agenda)的`关联 Issue`列尽可能把分享的讨论流程全覆盖，可以重复放入**推荐Issue**，并且附带其他相关的讨论或资源链接。
> 
> 其他问题：[agenda](https://github.com/X-lab2017/open-research/tree/main/agenda)的`关联 Issue`列是否需要像[openlist](https://github.com/X-lab2017/open-research/blob/main/openlist.md)的`History`列一样，统一一下Issue的标签表示形式？

是的，我觉得是可以参考的，具体可以便运行边优化，不用一下子想得那么好，先简单起步来即可~
