### ISSUE TITLE
[PaperRec] 基于贡献分配的开源软件核心开发者评估

### ISSUE THREAD

**Issue by tyn1998** [X-lab2017/open-research#69]
## I wish to recommend a paper

- Title: 基于贡献分配的开源软件核心开发者评估
- Year: 2018
- Conference or Journal: 软件学报
- Rank: A
- Keywords:  开源软件, 核心开发者, 外围开发者, 贡献分配, 支持向量机
- Reason for Recommendation:
- Link: https://xlab2017.yuque.com/msdpvs/dtg7ew/26251097

@X-lab2017/x-lab-phd

**Comment by birdflyi** [comment]
PR #70 是非常简洁高效的入库改动~

改进建议：
根据`Keywords: 开源软件;核心开发者;外围开发者;贡献分配;支持向量机` 可以填入openlist表中的`Keywords`，暂时以英文逗号+空格分隔示例`Keyword1, Keyword2`。
@tyn1998 你还可以做得更好~

**Comment by tyn1998** [comment]
这就改~

**Comment by birdflyi** [comment]
可以的，先占个位~
