### ISSUE TITLE
[PaperRec] Quantitative Analysis of Community Evolution in Developer Social Networks Around Open Source Soware Projects

### ISSUE THREAD

**Issue by will-ww** [X-lab2017/open-research#75]
- **Title**: Quantitative Analysis of Community Evolution in Developer Social Networks Around Open Source Software Projects
- **Year**: 2022
- **Conference or Journal**: arxiv
- **Rank**: -
- **Keywords**: Developer Social Networks, Community Evolution Patterns, Entropy-Bases Indices, Open Source Software, Mining Software Repositories
- **Reason for Recommendation**: 张琰彬老师在南京大学那边的 DevOps 工作中看到的，特此推荐
- Link: https://arxiv.org/abs/2205.09935

**Comment by AliceCodeZhang** [comment]
这边文章分析软件研发过程中的开发者交接过程的影响因素，这种软工角度分析的方法值得大家研究一下
