### ISSUE TITLE
升级新的表单功能

### ISSUE THREAD

**Issue by will-ww** [X-lab2017/open-research#78]
体验一下：https://github.com/hypertrons/hypertrons-crx/issues/new/choose

相关PR：https://github.com/hypertrons/hypertrons-crx/pull/360

从[Echarts](https://github.com/apache/echarts/issues/new/choose)仓库学来的~目前表单功能只支持issue template，还不支持PR template。

_Originally posted by @tyn1998 in https://github.com/X-lab2017/open-wonderland/discussions/68_

感觉挺不错，OpenResearch 也升级下？@xiaoya-Esther

**Comment by will-ww** [comment]
https://github.com/X-lab2017/open-research/issues/83

![image](https://user-images.githubusercontent.com/15010826/171801562-f6a29e5b-0cbc-431f-9053-59b9032dee64.png)

我的意思是，审计成这种可以填空型的表单模板~

现在变成了 Checklist 的模样，这个当然也有用途，但应该不在这里~ @xiaoya-Esther 

![image](https://user-images.githubusercontent.com/15010826/171801777-89aae4c1-2d1a-4a46-b0f1-0d0db8c14857.png)

**Comment by xiaoya-Esther** [comment]
我再研究下🤔

**Comment by xiaoya-Esther** [comment]
基于一段时间的使用，感觉 Issue Template 中有些 label 和 tag 不够一目了然，目的不是很明确，建议：
- 论文推荐，template名字继续使用 Paper Recommendation，issue开头由 [PaperRec] 改为 [Recommendation]，打上 'paper' 的标签
- 论文分享，template名字由 Reading Plan Proposal 改为 Paper Presentation，issue开头由 [OpenPro] 改为 [Presentation]，打上 'paper' 的标签

#93
