### ISSUE TITLE
[Maintenance] 日常维护

### ISSUE THREAD

**Issue by birdflyi** [X-lab2017/open-research#8]
# 日常维护（Routine maintenance）
1. 更新说明文档
2. 优化目录结构
3. 解决bug
4. 更新文献等资源信息和Tag分类信息

**Comment by will-ww** [comment]
你这个是提出一个仓库下的任务吗？可否描述下目的？ @birdflyi

**Comment by birdflyi** [comment]
是针对这个仓库的美观、易用性的issue，可以长期开启。目的是比较小的非功能性维护，不对整体流程、计划和项目结构产生大的影响。比如：
改错别字、调整语序、增加链接等对说明文档中的含义不影响的改动，
纠正和更新Paper的标签，
移动文献资源（不增删），
对文献资源目录的局部调整，而不影响说明文档的链接。

**Comment by birdflyi** [comment]
这种长期零散的任务，似乎应该用Tag来管理……

**Comment by will-ww** [comment]
> 这种长期零散的任务，似乎应该用Labels来管理……

没问题，先提出一些 idea，然后我们看用什么方式合适~

**Comment by bifenglin** [comment]
提议不要放PDF文件，我们可以利用网盘等工具做文件服务器，否则github网络太慢，git clone不下来。越往后肯定越来越大。

**Comment by birdflyi** [comment]
> 提议不要放PDF文件，我们可以利用网盘等工具做文件服务器，否则github网络太慢，git clone不下来。越往后肯定越来越大。

赞同提议：考虑到网络问题，优先使用URL链接的形式给出资源位置，其次文件服务器链接（可以考虑统一开一个这样的文件服务或使用统一的云盘，上传PDF到文件服务器中，再以链接形式给出资源为主），最后是上传少量具有特殊意义或难以获取的PDF。

**Comment by xgdyp** [comment]
> > 提议不要放PDF文件，我们可以利用网盘等工具做文件服务器，否则github网络太慢，git clone不下来。越往后肯定越来越大。
> 
> 赞同提议：考虑到网络问题，优先使用URL链接的形式给出资源位置，其次文件服务器链接（可以考虑统一开一个这样的文件服务或使用统一的云盘，上传PDF到文件服务器中，再以链接形式给出资源为主），最后是上传少量具有特殊意义或难以获取的PDF。

我也觉得不要放了吧 我们可以放上文章的链接～

**Comment by will-ww** [comment]
好，那就这么定，论文可以放云上的一个仓库下~
