### ISSUE TITLE
移除结尾 A、B 两个内容到其它地方

### ISSUE THREAD

**Issue by will-ww** [X-lab2017/open-research#81]
openlist.md 文件中仅保留论文库清单和相关说明，其它可以放到其它地方，通过链接的形式进入（如果有必要）。

https://github.com/X-lab2017/open-research/blob/main/openlist.md

- [ ] A. 论文收集流程图（搬家）
- [ ] B. Directory Tree（搬家）

**Comment by birdflyi** [comment]
Related Issue #47 .

**Comment by birdflyi** [comment]
- [ ] C. 删除加粗编号表示历史分享功能

**Comment by will-ww** [comment]
Many thanks~
