### ISSUE TITLE
[整理] 软件工程知识领域的 mindmap

### ISSUE THREAD

**Issue by will-ww** [X-lab2017/open-research#96]
软件工程是开展开源研究的一个重要工具手段，整理一个软件工程知识领域的mindmap：

- 参考：https://xlab2017.yuque.com/msdpvs/me6vqg/gm5o23
- 输入：https://xlab2017.yuque.com/msdpvs/fzem1h/26163822
- 输出：https://xlab2017.yuque.com/msdpvs/me6vqg/gs99b2

**Comment by longyanz** [comment]
已初步完成~有什么需要修改的地方我再去进行改正~

**Comment by longyanz** [comment]
已初步完成，有什么需要修改的地方我再去改。

**Comment by will-ww** [comment]
> 已初步完成，有什么需要修改的地方我再去改。

Many thanks~
