### ISSUE TITLE
[开题框架] 大规模实训环境下基于kubernetes的弹性编排调度策略设计

### ISSUE THREAD

**Issue by JingbenShi668** [X-lab2017/open-research#98]
### Description

**开题题目**
大规模实训环境下基于kubernetes的弹性编排调度策略设计

**研究对象**
kubernetes中各节点的负载调度情况

**研究目标**
1. 构建kubernetes负载的预测模型
2. 设计基于kubernetes的响应式动态伸缩模型
3. 实现kubernetes负载的预测系统以及针对kubernetes的响应式动态伸缩算法
4. 建立负载预测模型与评价系统

**研究内容**
本课题旨在构建大规模实训环境下针对kubernetes负载的预测模型以及基于kubernetes的响应式动态伸缩模型，其中，基于kubernetes负载的预测模型可以预测流量变化所带来的集群负载变化，而基于kubernetes的响应式动态伸缩模型可以动态计算预测模型输出负载数据所需要的副本数。相比kubernetes默认调度算法仅考虑CPU和内存的使用率作为Node节点的资源评估，此响应式动态伸缩模型会将cpu、内存、workQueue、节点上请求的QPS数据作为节点资源评估的重要指标，从而实现关于更全面的节点资源评估。
其中，响应式动态伸缩模型中针对kubernetes的响应式动态伸缩算法，会实时计算kubernetes集群中资源与负载的情况，从而在kubernetes集群负载流量发生变化时，能够对kubernetes集群动态进行"削峰填谷"式的负载-资源匹配计算以及对对负载进行调度。

**研究方法**
本课题所采取的研究方法有文献研究法、实验分析法。
(1)文献研究法: 在学术平台检索与该课题相关的文献资料，仔细整理、分析，以了解目前该课题的研究现状以及相关问题对应的解决方案，从而较为全面地掌握研究该课题所需的信息，从而为该课题研究提供坚实、可靠的理论基础。
(2)实验分析法: 在针对该课题进行理论研究的同时，不断通过编程实现的方式来验证、改进研究内容。其中，需要构建并实现相关模型，并对模型性能、效率等进行相关分析、验证，以此验证理论研究的正确性，从而发现研究中存在的问题和不足，以此来不断提升研究模型。

**研究结果** 
构建基于预测式的k8s动态弹性收缩调度策略，从而在大规模实训场景下减少用户请求服务的等待时间，提升k8s集群中资源的利用率。

**实验方案** 
依托水杉在线平台的大规模实训场景，收集5周内学生申请创建容器的请求记录，基于前四周数据的流量请求数据作为k8s负载预测模型的基础数据，预测出类似实训课程在第5周的请求趋势走向，将预测数据与第5周的实际请求数据做比较，不断调整预测模型，实现较高精度预测，从而归纳出大规模实训场景下，一般的请求趋势走向；构建自定义k8s响应式动态弹性伸缩策略，将k8s集群中节点的数据cpu、内存、workQueue、节点上请求的QPS等数据作为节点资源评估的重要表指标，计算节点与负载之间的匹配度，从而进行k8s集群负载中的动态调度、调节；并且自定义k8s响应式动态伸缩模型会根据负载预测模型的预测输出数据提前进行pod副本的扩缩容；最终将此预测式动态弹性调度模型与k8s默认的调度模型进行对比分析，验证此课题所设计调度模型的优势。

**Comment by will-ww** [comment]
几点建议：

- 题目中可以不用专门突出kubernetes，以显示你的方法的通用性
- 例如：大规模实训环境下的弹性编排调度策略与预测模型
- 最好能说清楚你具体采用的方法，利于基于什么技术的
- 实验设计也需要细化下，workload是什么、数据是什么、指标是什么等

其它 OK~
